let data;

export default data = [
  {
    firstName: 'Adam',
    lastName: 'Lohnes',
    photo: 'https://avatars.githubusercontent.com/u/66277829?v=4',
    searchEndDate: new Date(2022, 3, 19),
    company: 'https://clickup.com/images/schema_org/logo.png',
    industry: null,
    stack: 'Front',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Cam',
    lastName: 'Colaco',
    photo: 'https://avatars.githubusercontent.com/u/78557835?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Chris',
    lastName: 'Lazzarini',
    photo: 'https://avatars.githubusercontent.com/u/49167372?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Chris',
    lastName: 'Turcios',
    photo: 'https://avatars.githubusercontent.com/u/77170411?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Clayton',
    lastName: 'Watterson',
    photo: 'https://avatars.githubusercontent.com/u/3577150?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
  },
  {
    firstName: 'Jake',
    lastName: 'Caughern',
    photo: 'https://avatars.githubusercontent.com/u/80003881?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Joey',
    lastName: 'Dowling',
    photo: 'https://avatars.githubusercontent.com/u/77697842?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Josh',
    lastName: 'Fuqua',
    photo: 'https://avatars.githubusercontent.com/u/79943156?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Juan',
    lastName: 'Acosta',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/v1646280016/s5hjbgyue24bp624ijbn.png',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Julie',
    lastName: 'Yu',
    photo: 'https://avatars.githubusercontent.com/u/69382434?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Maggie',
    lastName: 'Saldivia',
    photo: 'https://avatars.githubusercontent.com/u/13864148?v=4',
    searchEndDate: new Date(2022, 3, 21),
    company: 'https://s29.q4cdn.com/628966176/files/design/nav_gif.gif',
    industry: 'Finance',
    stack: 'Back',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Mary',
    lastName: 'Miyamoto',
    photo: 'https://avatars.githubusercontent.com/u/82669320?v=4',
    searchEndDate: null,
    company: null,
    industry: 'null',
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Maxine',
    lastName: 'Majnaric',
    photo: 'https://avatars.githubusercontent.com/u/64869554?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Lapid',
    photo: 'https://avatars.githubusercontent.com/u/19236670?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Lee',
    photo: 'https://avatars.githubusercontent.com/u/82406930?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Pollens',
    photo: 'https://avatars.githubusercontent.com/u/71514552?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Poyraz',
    lastName: 'Akay',
    photo: 'https://avatars.githubusercontent.com/u/81498700?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Rick',
    lastName: 'Kunz',
    photo: 'https://avatars.githubusercontent.com/u/19396164?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Sangeetha',
    lastName: 'Nair',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/v1646280016/s5hjbgyue24bp624ijbn.png',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yitong',
    lastName: 'Liu',
    photo: 'https://avatars.githubusercontent.com/u/83916460?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yu',
    lastName: 'Zhang',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/v1646280016/s5hjbgyue24bp624ijbn.png',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yuanqi',
    lastName: 'Wang',
    photo: 'https://avatars.githubusercontent.com/u/26532717?v=4',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
];
