let data;

export default data = [
  {
    firstName: 'Adam',
    lastName: 'Lohnes',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: new Date(2022, 3, 19),
    company: null,
    industry: null,
    stack: 'Front',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Cam',
    lastName: 'Colaco',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Chris',
    lastName: 'Lazzarini',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Chris',
    lastName: 'Turcios',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Clayton',
    lastName: 'Watterson',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
  },
  {
    firstName: 'Jake',
    lastName: 'Caughern',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Joey',
    lastName: 'Dowling',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Josh',
    lastName: 'Fuqua',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Juan',
    lastName: 'Acosta',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Julie',
    lastName: 'Yu',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Maggie',
    lastName: 'Saldivia',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: new Date(2022, 3, 21),
    company: null,
    industry: 'Finance',
    stack: 'Back',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Mary',
    lastName: 'Miyamoto',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: 'null',
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Maxine',
    lastName: 'Majnaric',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Lapid',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Lee',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Pollens',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Poyraz',
    lastName: 'Akay',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Rick',
    lastName: 'Kunz',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Sangeetha',
    lastName: 'Nair',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yitong',
    lastName: 'Liu',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yu',
    lastName: 'Zhang',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yuanqi',
    lastName: 'Wang',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/w_256,h_256,c_thumb,g_face/Julie_portrait_gkhxue.jpg',
    searchEndDate: null,
    company: null,
    industry: null,
    stack: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
];
