let data;
// potentially add demographic data

export default data = [
  {
    firstName: 'Adam',
    lastName: 'Lohnes',
    photo: 'https://avatars.githubusercontent.com/u/66277829?v=4',
    searchEndDate: new Date(2022, 3, 19),
    company: 'ClickUp',
    companyLogo: 'https://clickup.com/images/schema_org/logo.png',
    industry: null,
    role: 'Front-End Engineer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Cam',
    lastName: 'Colaco',
    photo: 'https://avatars.githubusercontent.com/u/78557835?v=4',
    searchEndDate: null,
    company: 'GoodLeap',
    companyLogo: 'https://goodleap.com/newsroom/GoodLeapOrangeGradientLogo.png',
    industry: null,
    role: 'Software Engineer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Chris',
    lastName: 'Lazzarini',
    photo: 'https://avatars.githubusercontent.com/u/49167372?v=4',
    searchEndDate: null,
    company: 'Google',
    companyLogo:
      'https://assets.stickpng.com/images/580b57fcd9996e24bc43c51f.png',
    industry: null,
    role: 'Strategy & Operations Lead',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Chris',
    lastName: 'Turcios',
    photo: 'https://avatars.githubusercontent.com/u/77170411?v=4',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: null,
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Clayton',
    lastName: 'Watterson',
    photo: 'https://avatars.githubusercontent.com/u/3577150?v=4',
    searchEndDate: null,
    company: 'Bestpass',
    companyLogo: 'https://bestpass.com/images/Bestpass_logo_blue_w_white.png',
    industry: null,
    role: 'Software Engineer',
  },
  {
    firstName: 'Jake',
    lastName: 'Caughern',
    photo: 'https://avatars.githubusercontent.com/u/80003881?v=4',
    searchEndDate: null,
    company: 'Booz Allen Hamilton',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Booz_Allen_Hamilton_logo.svg/1280px-Booz_Allen_Hamilton_logo.svg.png',
    industry: null,
    role: 'Junior Developer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Joey',
    lastName: 'Dowling',
    photo: 'https://avatars.githubusercontent.com/u/77697842?v=4',
    searchEndDate: null,
    company: 'UCLA Health',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/UCLA_Health_logo.svg/1200px-UCLA_Health_logo.svg.png',
    industry: null,
    role: 'Web Developer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Josh',
    lastName: 'Fuqua',
    photo: 'https://avatars.githubusercontent.com/u/79943156?v=4',
    searchEndDate: null,
    company: 'LeaseQuery',
    companyLogo:
      'https://lfp4z1317gc22cff3hs4vn8x-wpengine.netdna-ssl.com/wp-content/uploads/2021/06/leasequery-logo.png',
    industry: null,
    role: 'Software Engineer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Juan',
    lastName: 'Acosta',
    photo:
      'https://res.cloudinary.com/xoxohorses/image/upload/v1646280016/s5hjbgyue24bp624ijbn.png',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: null,
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Julie',
    lastName: 'Yu',
    photo: 'https://avatars.githubusercontent.com/u/69382434?v=4',
    searchEndDate: new Date(2022, 4, 27),
    company: 'Notion',
    companyLogo:
      'https://seeklogo.com/images/N/notion-logo-4CE8FBF5C5-seeklogo.com.png',
    industry: null,
    role: 'Software Engineer',
    applications: 6,
    interviews: 2,
    offers: 1,
    bypass: 0,
  },
  {
    firstName: 'Maggie',
    lastName: 'Saldivia',
    photo: 'https://avatars.githubusercontent.com/u/13864148?v=4',
    searchEndDate: new Date(2022, 3, 21),
    company: 'Block',
    companyLogo: 'https://s29.q4cdn.com/628966176/files/design/nav_gif.gif',
    industry: 'Finance',
    role: 'Back-End Engineer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Mary',
    lastName: 'Miyamoto',
    photo: 'https://avatars.githubusercontent.com/u/82669320?v=4',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: 'null',
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Maxine',
    lastName: 'Majnaric',
    photo: 'https://avatars.githubusercontent.com/u/64869554?v=4',
    searchEndDate: null,
    company: 'DXC Technology',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/DXC_Technology_logo_%282021%29.svg/360px-DXC_Technology_logo_%282021%29.svg.png',
    industry: null,
    role: 'Full-Stack Developer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Lapid',
    photo: 'https://avatars.githubusercontent.com/u/19236670?v=4',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: null,
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Lee',
    photo: 'https://avatars.githubusercontent.com/u/82406930?v=4',
    searchEndDate: null,
    company: 'Genentech',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Genentech.svg/1280px-Genentech.svg.png',
    industry: null,
    role: 'Software Engineer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Pollens',
    photo: 'https://avatars.githubusercontent.com/u/71514552?v=4',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: null,
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Poyraz',
    lastName: 'Akay',
    photo: 'https://avatars.githubusercontent.com/u/81498700?v=4',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: null,
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Rick',
    lastName: 'Kunz',
    photo: 'https://avatars.githubusercontent.com/u/19396164?v=4',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: null,
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Sangeetha',
    lastName: 'Nair',
    photo: 'https://avatars.githubusercontent.com/u/61399518?v=4',
    searchEndDate: null,
    company: 'Infosys',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/1280px-Infosys_logo.svg.png',
    industry: null,
    role: 'Technology Analyst',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yitong',
    lastName: 'Liu',
    photo: 'https://avatars.githubusercontent.com/u/83916460?v=4',
    searchEndDate: null,
    company: 'Amazon Web Services',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1024px-Amazon_Web_Services_Logo.svg.png',
    industry: null,
    role: 'Software Engineer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yu',
    lastName: 'Zhang',
    photo: 'https://avatars.githubusercontent.com/u/83844510?v=4',
    searchEndDate: null,
    company: null,
    companyLogo: null,
    industry: null,
    role: null,
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
  {
    firstName: 'Yuanqi',
    lastName: 'Wang',
    photo: 'https://avatars.githubusercontent.com/u/26532717?v=4',
    searchEndDate: null,
    company: 'Plaid',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Plaid_logo.svg/252px-Plaid_logo.svg.png?20200225180658',
    industry: null,
    role: 'Software Engineer',
    applications: 0,
    interviews: 0,
    offers: 0,
    bypass: 0,
  },
];
